"""
generate_option_homework_report.py
==================================
Create the final Word/PDF homework report for the minute futures option task.

The report uses the processed QuantConnect/LEAN public sample data and the
output generated by option_iv_rv_greeks.py.
"""

from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path

import pandas as pd
from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Inches, Pt, RGBColor
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[1]
DATA_CSV = ROOT / "data/processed/quantconnect_es_future_option_minute.csv"
OUTPUT_DIR = ROOT / "research/outputs/es_options"
SUMMARY_CSV = OUTPUT_DIR / "option_latest_summary.csv"
ATTR_CSV = OUTPUT_DIR / "option_price_attribution.csv"
VOL_STATS_CSV = OUTPUT_DIR / "daily_volatility_summary.csv"
SUMMARY_JSON = OUTPUT_DIR / "option_analysis_summary.json"
HIST_JSON = OUTPUT_DIR / "historical_percentiles.json"
IV_RV_FIG = OUTPUT_DIR / "iv_vs_rv.png"
ATTR_FIG = OUTPUT_DIR / "price_attribution.png"
SUBMISSION_NAME = "23300180062_任昊来_第八周作业"
PACKAGE_PARENT = ROOT / "作业提交包" / "_staging"
PACKAGE_DIR = PACKAGE_PARENT / SUBMISSION_NAME
REPORT_DOCX = PACKAGE_DIR / f"{SUBMISSION_NAME}.docx"
REPORT_PDF = PACKAGE_DIR / f"{SUBMISSION_NAME}.pdf"


def ensure_package_dir() -> None:
    if PACKAGE_DIR.exists():
        shutil.rmtree(PACKAGE_DIR)
    PACKAGE_DIR.mkdir(parents=True, exist_ok=True)
    for sub in ["code", "data", "outputs"]:
        (PACKAGE_DIR / sub).mkdir(exist_ok=True)


def copy_artifacts() -> None:
    files = [
        (ROOT / "research/option_iv_rv_greeks.py", PACKAGE_DIR / "code/option_iv_rv_greeks.py"),
        (ROOT / "research/prepare_quantconnect_es_option_data.py", PACKAGE_DIR / "code/prepare_quantconnect_es_option_data.py"),
        (ROOT / "research/prepare_historical_percentiles.py", PACKAGE_DIR / "code/prepare_historical_percentiles.py"),
        (ROOT / "research/generate_option_homework_report.py", PACKAGE_DIR / "code/generate_option_homework_report.py"),
        (DATA_CSV, PACKAGE_DIR / "data/quantconnect_es_future_option_minute.csv"),
        (ROOT / "data/processed/yahoo_es_vix_history_2015_2020.csv", PACKAGE_DIR / "data/yahoo_es_vix_history_2015_2020.csv"),
        (ROOT / "data/quantconnect_raw/es/future_20200106_quote.zip", PACKAGE_DIR / "data/quantconnect_es_future_quote_raw.zip"),
        (ROOT / "data/quantconnect_raw/es/option_20200106_quote_american.zip", PACKAGE_DIR / "data/quantconnect_es_option_quote_raw.zip"),
        (SUMMARY_CSV, PACKAGE_DIR / "outputs/option_latest_summary.csv"),
        (ATTR_CSV, PACKAGE_DIR / "outputs/option_price_attribution.csv"),
        (VOL_STATS_CSV, PACKAGE_DIR / "outputs/daily_volatility_summary.csv"),
        (OUTPUT_DIR / "option_iv_rv_greeks.csv", PACKAGE_DIR / "outputs/option_iv_rv_greeks.csv"),
        (OUTPUT_DIR / "historical_percentiles.csv", PACKAGE_DIR / "outputs/historical_percentiles.csv"),
        (OUTPUT_DIR / "historical_percentiles.json", PACKAGE_DIR / "outputs/historical_percentiles.json"),
        (IV_RV_FIG, PACKAGE_DIR / "outputs/iv_vs_rv.png"),
        (ATTR_FIG, PACKAGE_DIR / "outputs/price_attribution.png"),
    ]
    for src, dst in files:
        if src.exists():
            shutil.copy2(src, dst)


def write_package_readme() -> None:
    readme = PACKAGE_DIR / "README.txt"
    readme.write_text(
        "\n".join(
            [
                "期货期权1分钟数据 IV/RV、希腊字母与价格归因作业包",
                "",
                "主要文件：",
                f"1. {SUBMISSION_NAME}.docx：正式Word作业报告。",
                f"2. {SUBMISSION_NAME}.pdf：正式PDF作业报告。",
                "3. code/prepare_quantconnect_es_option_data.py：下载并转换公开样本数据。",
                "4. code/option_iv_rv_greeks.py：计算IV、RV、历史分位、希腊字母和价格归因。",
                "5. code/prepare_historical_percentiles.py：用Yahoo ES=F和VIX历史数据计算历史分位代理。",
                "6. code/generate_option_homework_report.py：生成DOCX/PDF和本提交包。",
                "7. data/：原始公开样本zip、处理后的分钟CSV和Yahoo历史CSV。",
                "8. outputs/：计算结果表和图形。",
                "",
                "复现命令：",
                "python research/prepare_quantconnect_es_option_data.py",
                "python research/option_iv_rv_greeks.py --input data/processed/quantconnect_es_future_option_minute.csv --output-dir research/outputs/es_options --rv-window 60 --percentile-window 390 --minutes-per-year 347760 --rate 0.015",
                "python research/prepare_historical_percentiles.py",
                "python research/generate_option_homework_report.py",
                "",
                f"当前提交命名：{SUBMISSION_NAME}",
            ]
        ),
        encoding="utf-8",
    )


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def set_cell_text(cell, text: str, bold: bool = False, color: RGBColor | None = None) -> None:
    cell.text = ""
    paragraph = cell.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(text)
    run.bold = bold
    if color:
        run.font.color.rgb = color
    run.font.size = Pt(9)


def style_table(table, header_fill: str = "1F4E79") -> None:
    table.style = "Table Grid"
    for row_idx, row in enumerate(table.rows):
        for cell in row.cells:
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
            for paragraph in cell.paragraphs:
                paragraph.paragraph_format.space_after = Pt(0)
                for run in paragraph.runs:
                    run.font.name = "Microsoft YaHei"
                    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
                    run.font.size = Pt(9)
        if row_idx == 0:
            for cell in row.cells:
                set_cell_shading(cell, header_fill)
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.bold = True
                        run.font.color.rgb = RGBColor(255, 255, 255)


def add_heading(document: Document, text: str, level: int) -> None:
    paragraph = document.add_heading(text, level=level)
    for run in paragraph.runs:
        run.font.name = "Microsoft YaHei"
        run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        run.font.color.rgb = RGBColor(31, 78, 121)


def add_paragraph(document: Document, text: str, bold_lead: str | None = None) -> None:
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.first_line_indent = Pt(18)
    paragraph.paragraph_format.line_spacing = 1.18
    paragraph.paragraph_format.space_after = Pt(6)
    if bold_lead and text.startswith(bold_lead):
        lead = paragraph.add_run(bold_lead)
        lead.bold = True
        paragraph.add_run(text[len(bold_lead) :])
    else:
        paragraph.add_run(text)
    for run in paragraph.runs:
        run.font.name = "Microsoft YaHei"
        run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        run.font.size = Pt(10.5)


def add_bullet(document: Document, text: str) -> None:
    paragraph = document.add_paragraph(style="List Bullet")
    paragraph.paragraph_format.line_spacing = 1.12
    paragraph.paragraph_format.space_after = Pt(3)
    run = paragraph.add_run(text)
    run.font.name = "Microsoft YaHei"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(10)


def pct(x: float) -> str:
    if pd.isna(x):
        return ""
    return f"{x:.2%}"


def num(x: float, digits: int = 4) -> str:
    if pd.isna(x):
        return ""
    return f"{x:.{digits}f}"


def short_symbol(symbol: str) -> str:
    return (
        str(symbol)
        .replace("OG-CALL-", "C")
        .replace("OG-PUT-", "P")
        .replace("ES-CALL-", "C")
        .replace("ES-PUT-", "P")
        .replace("-2020", "-")
    )


def vol_summary(stats: pd.DataFrame) -> dict[str, float]:
    return {
        "iv_min": float(stats["iv_min"].min()),
        "iv_max": float(stats["iv_max"].max()),
        "iv_median": float(stats["iv_median"].mean()),
        "rv_latest": float(stats["rv_latest"].mean()),
        "rv_median": float(stats["rv_median"].mean()),
        "rv_mean": float(stats["rv_mean"].mean()),
        "rv_min": float(stats["rv_min"].min()),
        "rv_max": float(stats["rv_max"].max()),
        "max_gap": float(stats["max_gap_minutes"].max()),
    }


def set_column_widths(table, widths_cm: list[float]) -> None:
    table.autofit = False
    for row in table.rows:
        for idx, width in enumerate(widths_cm):
            if idx < len(row.cells):
                row.cells[idx].width = Cm(width)


def build_result_table(document: Document, latest: pd.DataFrame) -> None:
    for _, row in latest.iterrows():
        text = (
            f"{short_symbol(row['option_symbol'])}：K={num(row['strike'], 0)}，"
            f"F={num(row['futures_price'], 2)}，期权价={num(row['option_mid'], 2)}，"
            f"IV={pct(row['iv'])}（分位 {pct(row['iv_percentile'])}），"
            f"RV={pct(row['rv'])}（分位 {pct(row['rv_percentile'])}），"
            f"Delta={num(row['delta'], 4)}，Gamma={num(row['gamma'], 5)}，Vega={num(row['vega'], 2)}。"
        )
        add_bullet(document, text)


def build_attr_table(document: Document, attr_totals: pd.DataFrame) -> None:
    for _, row in attr_totals.iterrows():
        text = (
            f"{short_symbol(row['option_symbol'])}：价格变化={num(row['price_change'], 4)}，"
            f"Delta贡献={num(row['delta_effect'], 4)}，Gamma贡献={num(row['gamma_effect'], 4)}，"
            f"Vega贡献={num(row['vega_effect'], 4)}，Theta贡献={num(row['theta_effect'], 4)}，"
            f"残差={num(row['residual'], 4)}。"
        )
        add_bullet(document, text)


def build_docx() -> None:
    latest = pd.read_csv(SUMMARY_CSV)
    vol_stats = pd.read_csv(VOL_STATS_CSV)
    vol = vol_summary(vol_stats)
    with open(SUMMARY_JSON, "r", encoding="utf-8") as fh:
        summary = json.load(fh)
    with open(HIST_JSON, "r", encoding="utf-8") as fh:
        hist = json.load(fh)
    attr_totals = pd.DataFrame(summary["price_attribution_totals"]).T.reset_index(names="option_symbol")
    raw = pd.read_csv(DATA_CSV)

    document = Document()
    section = document.sections[0]
    section.top_margin = Cm(2.2)
    section.bottom_margin = Cm(2.0)
    section.left_margin = Cm(2.0)
    section.right_margin = Cm(2.0)

    styles = document.styles
    styles["Normal"].font.name = "Microsoft YaHei"
    styles["Normal"]._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    styles["Normal"].font.size = Pt(10.5)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_after = Pt(8)
    run = title.add_run("期货期权1分钟数据 IV/RV、希腊字母与价格变化解释")
    run.bold = True
    run.font.size = Pt(18)
    run.font.name = "Microsoft YaHei"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.color.rgb = RGBColor(31, 78, 121)

    meta = document.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.add_run(f"提交文件名：{SUBMISSION_NAME}    数据样本：CME ES期货与ES期货期权1分钟Quote")
    meta_run.font.size = Pt(10)
    meta_run.font.name = "Microsoft YaHei"
    meta_run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    document.add_paragraph()

    add_heading(document, "一、数据来源与处理", 1)
    add_paragraph(
        document,
        "本作业使用 QuantConnect/LEAN 开源仓库提供的公开样本数据。样本包括 CME E-mini S&P 500 期货 ES 的 1 分钟 quote 数据，以及 ES 期货期权的 1 分钟美式期权 quote 数据。原始文件为 LEAN 压缩格式，已由脚本转换为普通 CSV 后进行分析。",
    )
    add_paragraph(
        document,
        f"处理后的样本共 {len(raw)} 条记录，覆盖 {raw['option_symbol'].nunique()} 个期权合约。期货价格采用买卖盘收盘价中间值，期权价格采用期权买卖盘收盘价中间值，并过滤相对买卖价差超过 5% 的报价；无风险利率取 1.5%。",
    )
    add_paragraph(
        document,
        "我也测试了 Yahoo Finance / yfinance：GC=F、CL=F、ES=F 等期货可获取近期期货 1 分钟行情，但 GC=F、CL=F 的 futures option chain 返回为空；GLD、USO 等 ETF 有期权链快照，但不是期货期权逐分钟历史价格。因此本作业主分析采用 LEAN 公开期货期权分钟样本。此前检查到 COMEX 黄金期权公开样本太短且盘口价差过宽，所以没有作为最终主数据。",
    )

    add_heading(document, "二、计算方法", 1)
    add_bullet(document, "RV：用期货 1 分钟对数收益率的 60 分钟滚动标准差年化，公式为 RV = std(ln(F_t/F_{t-1})) * sqrt(N_year)。短窗口 RV 会比较嘈杂，因此同时报告末点、中位数和均值。")
    add_bullet(document, "IV：使用 Black-76 期货期权模型反解隐含波动率，因为期货期权的标的是期货价格 F。ES 样本为美式期权，本文使用 Black-76 作为作业中的欧式近似估值口径。")
    add_bullet(document, "分钟样本分位：当前 IV 或 RV 在当日滚动分钟窗口中小于等于自身的比例。本文采用 60 分钟 RV 窗口、390 分钟分位窗口。")
    add_bullet(document, "历史分位：由于公开期权分钟样本只有一个交易日，真正历史分位改用 Yahoo 历史代理计算：ES=F 日线收益率计算 RV20/RV60，VIX 作为 S&P/ES 期权 IV 代理。")
    add_bullet(document, "希腊字母：计算 Delta、Gamma、Vega、Theta、Rho，用于衡量期权价格对标的、波动率、时间和利率的敏感度。")
    add_bullet(document, "价格归因：按相邻分钟逐段计算并累计，dV ≈ Delta*dF + 0.5*Gamma*dF^2 + Vega*dIV + Theta*dt + Rho*dr + residual；因此不是简单用期末与期初的净变动做一次端点归因。")

    add_heading(document, "三、IV/RV 与希腊字母结果", 1)
    add_paragraph(
        document,
        "最新时点四个期权合约的 IV 高于当日分钟 RV，但当日分钟样本分位并不极端，说明期权隐含波动率相对当日实现波动有风险溢价，但不是样本内极端高位。由于公开期权分钟样本只有一个交易日，真正历史分位需要借助更长历史代理。",
    )
    build_result_table(document, latest)
    add_paragraph(
        document,
        f"日内波动统计：IV 是用每一分钟期权中间价逐点反解得到，并非把日频 IV 广播到分钟频率；四个合约的日内 IV 大致处于 {pct(vol['iv_min'])}-{pct(vol['iv_max'])}，中位数约 {pct(vol['iv_median'])}，所以图中看起来较平。60 分钟滚动 RV 的末点约 {pct(vol['rv_latest'])}，日内中位数约 {pct(vol['rv_median'])}、均值约 {pct(vol['rv_mean'])}，区间约 {pct(vol['rv_min'])}-{pct(vol['rv_max'])}。样本存在最长约 {vol['max_gap']:.0f} 分钟的报价缺口，图中在大缺口处断线，没有人为插值或前向填充。",
    )
    add_paragraph(
        document,
        f"历史代理分位：以 2020-01-06 为样本日，Yahoo ES=F 2015-2020 日线计算得到 RV20={pct(hist['rv20'])}，处于 {pct(hist['rv20_percentile'])} 分位；RV60={pct(hist['rv60'])}，处于 {pct(hist['rv60_percentile'])} 分位。同期 VIX={pct(hist['vix_iv_proxy'])}，处于 {pct(hist['vix_iv_proxy_percentile'])} 分位，可作为 ES/SPX 期权 IV 的历史分位代理。",
    )
    document.add_paragraph()
    if IV_RV_FIG.exists():
        document.add_picture(str(IV_RV_FIG), width=Inches(5.8))
        cap = document.add_paragraph("图1  逐分钟反解 IV 与 60 分钟滚动 RV 对比")
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER

    add_heading(document, "四、交易策略考虑", 1)
    add_paragraph(
        document,
        f"本样本最新时点 IV 约为 12.9%-14.2%，60 分钟滚动 RV 的末点约为 {pct(vol['rv_latest'])}，日内中位数约为 {pct(vol['rv_median'])}、均值约为 {pct(vol['rv_mean'])}。IV 高于短窗口 RV 的多数时点；但 VIX 历史代理分位约为 {pct(hist['vix_iv_proxy_percentile'])}，ES=F RV20 历史分位约为 {pct(hist['rv20_percentile'])}，都不属于极端高位。因此不宜简单裸卖波动率，更适合结合方向观点和风险预算做有限风险价差。",
    )
    add_bullet(document, "若有方向判断，可考虑牛市/熊市价差，用有限权利金表达方向，同时减少单腿买权的 Theta 损耗。")
    add_bullet(document, "若判断后续波动会上升，可考虑买入跨式或宽跨式；但当前 IV 已高于 RV，需要确认事件催化。")
    add_bullet(document, "若判断波动会回落，可考虑铁鹰或卖出价差等有限风险卖波动结构，不建议裸卖 Gamma。")
    add_bullet(document, "真实交易中应增加更长历史样本、成交量过滤、买卖价差过滤和 Delta 对冲成本测算。")

    add_heading(document, "五、期权价格变化解释", 1)
    add_paragraph(
        document,
        "从累计归因看，期权价格变化主要由期货价格变动、Gamma 非线性项、IV 变化和时间价值衰减共同解释。归因采用相邻分钟逐段累加，所以各合约的 Delta 项不是 Delta 乘以期初到期末的净期货涨跌，而是整条路径上 prev-Delta * 每分钟 dF 的累计。图2改为全天累计归因，并单独画 residual，以检验希腊字母解释项的误差。",
    )
    build_attr_table(document, attr_totals)
    document.add_paragraph()
    if ATTR_FIG.exists():
        document.add_picture(str(ATTR_FIG), width=Inches(5.8))
        cap = document.add_paragraph("图2  全天累计价格归因与残差")
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER

    add_heading(document, "六、结论", 1)
    add_paragraph(
        document,
        "本作业完成了期货期权 1 分钟数据分析的完整流程：公开样本下载与转换、RV 计算、Black-76 IV 反解、历史分位代理、希腊字母计算和价格变化归因。结果显示，ES 期货期权最新 IV 高于当日分钟 RV，但 VIX 历史代理分位处于中性区间，更适合结合方向判断采用有限风险价差，而不是仅凭 IV/RV 做激进裸卖波动率。",
    )

    add_heading(document, "七、代码与数据清单", 1)
    add_bullet(document, "research/prepare_quantconnect_es_option_data.py：下载并转换 QuantConnect/LEAN 样本数据。")
    add_bullet(document, "research/option_iv_rv_greeks.py：计算 IV、RV、历史分位、希腊字母和价格归因。")
    add_bullet(document, "data/processed/quantconnect_es_future_option_minute.csv：转换后的期货期权分钟数据。")
    add_bullet(document, "data/processed/yahoo_es_vix_history_2015_2020.csv：ES=F 与 VIX 历史数据，用于历史分位代理。")
    add_bullet(document, "research/outputs/es_options/：计算结果表、JSON 摘要和图形。")

    add_heading(document, "八、参考资料", 1)
    add_bullet(document, "QuantConnect 文档：US Future Options 数据说明，https://www.quantconnect.com/docs/v2/lean-cli/datasets/quantconnect/download-in-bulk/us-future-options")
    add_bullet(document, "QuantConnect/LEAN 开源仓库样本数据，https://github.com/QuantConnect/Lean")
    add_bullet(document, "Databento 文档：期货期权数据与 OHLCV 分钟聚合格式说明，https://databento.com/docs/schemas-and-data-formats")
    add_bullet(document, "yfinance 文档：历史行情和期权链接口，https://ranaroussi.github.io/yfinance/reference/index.html")

    footer = document.sections[0].footer.paragraphs[0]
    footer.text = f"{SUBMISSION_NAME} | 期货期权1分钟数据分析"
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.save(REPORT_DOCX)


def register_pdf_fonts() -> tuple[str, str]:
    regular = r"C:\Windows\Fonts\msyh.ttc"
    bold = r"C:\Windows\Fonts\msyhbd.ttc"
    pdfmetrics.registerFont(TTFont("MSYH", regular))
    pdfmetrics.registerFont(TTFont("MSYH-Bold", bold))
    return "MSYH", "MSYH-Bold"


def para(text: str, style) -> Paragraph:
    return Paragraph(text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), style)


def build_pdf() -> None:
    font, bold_font = register_pdf_fonts()
    latest = pd.read_csv(SUMMARY_CSV)
    vol_stats = pd.read_csv(VOL_STATS_CSV)
    vol = vol_summary(vol_stats)
    with open(SUMMARY_JSON, "r", encoding="utf-8") as fh:
        summary = json.load(fh)
    with open(HIST_JSON, "r", encoding="utf-8") as fh:
        hist = json.load(fh)
    attr_totals = pd.DataFrame(summary["price_attribution_totals"]).T.reset_index(names="option_symbol")

    doc = SimpleDocTemplate(str(REPORT_PDF), pagesize=A4, rightMargin=1.6 * cm, leftMargin=1.6 * cm, topMargin=1.6 * cm, bottomMargin=1.5 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("CNTitle", parent=styles["Title"], fontName=bold_font, fontSize=18, leading=24, alignment=TA_CENTER, textColor=colors.HexColor("#1F4E79"))
    h_style = ParagraphStyle("CNHeading", parent=styles["Heading1"], fontName=bold_font, fontSize=13, leading=18, spaceBefore=10, spaceAfter=6, textColor=colors.HexColor("#1F4E79"))
    body = ParagraphStyle("CNBody", parent=styles["BodyText"], fontName=font, fontSize=9.6, leading=15, firstLineIndent=18, spaceAfter=5)
    bullet = ParagraphStyle("CNBullet", parent=styles["BodyText"], fontName=font, fontSize=9.2, leading=13, leftIndent=12, bulletIndent=0, spaceAfter=3)
    cap = ParagraphStyle("CNCaption", parent=styles["BodyText"], fontName=font, fontSize=8.8, leading=12, alignment=TA_CENTER, textColor=colors.HexColor("#555555"))

    story = [
        Paragraph("期货期权1分钟数据 IV/RV、希腊字母与价格变化解释", title_style),
        Paragraph(f"提交文件名：{SUBMISSION_NAME}", ParagraphStyle("Meta", parent=body, alignment=TA_CENTER, firstLineIndent=0)),
        Spacer(1, 8),
        Paragraph("一、数据来源与处理", h_style),
        para("本作业使用 QuantConnect/LEAN 开源仓库提供的 CME E-mini S&P 500 期货 ES 和 ES 期货期权的 1 分钟 quote 样本。原始 LEAN 压缩文件已转换为普通 CSV，期货和期权价格均使用买卖盘收盘价中间值，并过滤相对买卖价差超过 5% 的报价。", body),
        para("Yahoo/yfinance 可获取 GC=F、CL=F 等期货 1 分钟行情，但 GC=F、CL=F 的期货期权链不可用；GLD、USO 有 ETF 期权链快照，但不是期货期权分钟历史价格，因此本文主分析采用 LEAN 公开样本。", body),
        Paragraph("二、方法", h_style),
        Paragraph("• RV：期货 1 分钟对数收益率的 60 分钟滚动标准差年化；短窗口 RV 较嘈杂，因此同时报告末点、中位数和均值。", bullet),
        Paragraph("• IV：使用 Black-76 期货期权模型反解隐含波动率；ES 样本为美式期权，本文采用欧式近似。", bullet),
        Paragraph("• 分位：分钟样本分位来自当日滚动窗口；真正历史分位用 Yahoo ES=F 的 RV 和 VIX 的 IV 代理。", bullet),
        Paragraph("• 价格归因：按相邻分钟逐段计算并累计，dV ≈ Delta*dF + 0.5*Gamma*dF^2 + Vega*dIV + Theta*dt + Rho*dr + residual。", bullet),
        Paragraph("三、结果", h_style),
    ]

    result_data = [["合约", "类型", "K", "F", "期权价", "IV", "IV分位", "RV", "RV分位", "Delta", "Vega"]]
    for _, row in latest.iterrows():
        result_data.append([
            row["option_symbol"],
            row["option_type"],
            num(row["strike"], 0),
            num(row["futures_price"], 2),
            num(row["option_mid"], 2),
            pct(row["iv"]),
            pct(row["iv_percentile"]),
            pct(row["rv"]),
            pct(row["rv_percentile"]),
            num(row["delta"], 3),
            num(row["vega"], 1),
        ])
    table = Table(result_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), font, 7.0),
        ("FONT", (0, 0), (-1, 0), bold_font, 7.2),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CCCCCC")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
    ]))
    story.extend([table, Spacer(1, 8)])
    story.append(
        para(
            f"日内波动统计：IV 是逐分钟用 Black-76 反解，不是日频 IV 广播；四个合约日内 IV 约处于 {pct(vol['iv_min'])}-{pct(vol['iv_max'])}，中位数约 {pct(vol['iv_median'])}。60 分钟滚动 RV 的末点约 {pct(vol['rv_latest'])}，日内中位数约 {pct(vol['rv_median'])}、均值约 {pct(vol['rv_mean'])}，区间约 {pct(vol['rv_min'])}-{pct(vol['rv_max'])}。样本最长报价缺口约 {vol['max_gap']:.0f} 分钟，图中大缺口处断线，没有人为插值或前向填充。",
            body,
        )
    )
    if IV_RV_FIG.exists():
        story.extend([Image(str(IV_RV_FIG), width=15 * cm, height=7 * cm), Paragraph("图1  逐分钟反解 IV 与 60 分钟滚动 RV 对比", cap)])

    story.extend([
        Paragraph("四、策略建议", h_style),
        para(f"样本最新时点四个期权合约 IV 约为 12.9%-14.2%，60 分钟滚动 RV 末点约 {pct(vol['rv_latest'])}，日内中位数约 {pct(vol['rv_median'])}、均值约 {pct(vol['rv_mean'])}。历史代理显示：ES=F RV20 位于 {pct(hist['rv20_percentile'])} 分位，VIX 位于 {pct(hist['vix_iv_proxy_percentile'])} 分位，均非极端高位。结论是：更适合结合方向判断采用有限风险价差；若做波动率交易，应避免裸卖 Gamma。", body),
        Paragraph("五、价格变化解释", h_style),
        para("归因采用相邻分钟逐段累加，所以各合约的 Delta 项不是 Delta 乘以期初到期末的净期货涨跌，而是整条路径上 prev-Delta * 每分钟 dF 的累计。图2为全天累计归因，并把 residual 单独画成子图。", body),
    ])
    attr_data = [["合约", "价格变化", "Delta", "Gamma", "Vega", "Theta", "残差"]]
    for _, row in attr_totals.iterrows():
        attr_data.append([
            row["option_symbol"],
            num(row["price_change"], 3),
            num(row["delta_effect"], 3),
            num(row["gamma_effect"], 3),
            num(row["vega_effect"], 3),
            num(row["theta_effect"], 3),
            num(row["residual"], 3),
        ])
    attr_table = Table(attr_data, repeatRows=1)
    attr_table.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), font, 7.0),
        ("FONT", (0, 0), (-1, 0), bold_font, 7.2),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CCCCCC")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
    ]))
    story.extend([attr_table, Spacer(1, 8)])
    if ATTR_FIG.exists():
        story.extend([Image(str(ATTR_FIG), width=15 * cm, height=7 * cm), Paragraph("图2  全天累计价格归因与残差", cap)])

    story.extend([
        Paragraph("六、结论与附件", h_style),
        para("本作业完成了数据获取、IV/RV 分位、希腊字母和期权价格归因。附件目录包含全部代码、原始样本、处理后数据和结果表。参考资料包括 QuantConnect 文档与 LEAN 仓库、Databento 数据格式说明、yfinance 文档。", body),
    ])
    doc.build(story)


def make_zip() -> Path:
    zip_path = ROOT / "作业提交包" / f"{SUBMISSION_NAME}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path in PACKAGE_DIR.rglob("*"):
            if path.is_file():
                zf.write(path, path.relative_to(PACKAGE_PARENT))
    return zip_path


def main() -> None:
    ensure_package_dir()
    copy_artifacts()
    write_package_readme()
    build_docx()
    build_pdf()
    zip_path = make_zip()
    print(f"DOCX: {REPORT_DOCX}")
    print(f"PDF: {REPORT_PDF}")
    print(f"ZIP: {zip_path}")


if __name__ == "__main__":
    main()
